[package]
name = "butter"
version = "0.1.0"
edition = "2021"
authors = ["Zhangyuan Nie"]
license = "GPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "butterd"
path = "src/daemon/main.rs"

[[bin]]
name = "butter"
path = "src/main.rs"

[dependencies]
gtk = { version = "0.4", package = "gtk4" }
adw = { version = "0.1", package = "libadwaita" }
regex = "1.5"
serde = "1.0"
serde_json = "1.0"
