[package]
name = "butter"
version = "0.1.0"
edition = "2021"
authors = ["Zhangyuan Nie"]
license = "GPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.4", package = "gtk4" }
adw = { version = "0.1", package = "libadwaita" }
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
gettext = { version = "0.7", package = "gettext-rs", features = ["gettext-system"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
