[package]
name = "rpc"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dependencies.rpc-macros]
path = "../rpc-macros"
version = "0.1.0"
